spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/blog-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  mvc:
    view:
      prefix: /
      suffix: .html
    pathmatch:
      matching-strategy: ant_path_matcher






server:
  port: 8082
